### ISSUE TITLE
nspages support?

### ISSUE THREAD

**Issue by LunaticZorr** [dokufreaks/plugin-pagelist#106]
Hello!

I've been trying to use your plugin together with [nspages ](https://www.dokuwiki.org/plugin:nspages), since it seems pagelist only needs a list of pages, correct?

Using the following code:

`<nspages mvr:issues -h1 -textPages="" -simpleList -nbItemsMax=10>`

I should get a list of 10 pages from the _mvr:issues_ namespace. This works. But if I use the following code to use this list with your plugin, I get noting back. No list, just an empty space.

`<pagelist&noheader&table>`
`<nspages mvr:issues -h1 -textPages="" -simpleList -nbItemsMax=10>`
`</pagelist>`

![Image](https://42cdn.com/b2api/v1/b2_download_file_by_id?fileId=4_z6177fca890d8c37157cc0814_f114f308e9f35f892_d20171027_m124618_c001_v0001092_t0024)

Any idea if it is possible to use these two plugins together?

**Comment by KevinMaschke** [comment]
Bumping it :)

**Comment by LarsGit223** [comment]
@KevinMaschke:
That approach will not work. The pagelist plugin simply takes all content between the ```<pagelist>``` tags and processes it. If other plugin tags are included in-between them then the other plugins won't work/won't be called/executed.

But I think the **dir** plugin might do what you want, see https://www.dokuwiki.org/plugin:dir.

**Comment by Klap-in** [comment]
Plugins inside the `<pagelist>...</pagelist>`syntax are not supported. Only the other way around is supported, that other plugins call pagelist internally for printing the list.
