### ISSUE TITLE
Support for inline style, render as a comma-separated list of results

### ISSUE THREAD

**Issue by kruff-a-lon** [dokufreaks/plugin-pagelist#107]
I think it would be fantastic if it was possible to use a **style** called **inline** to render the results as a comma-separated list of results. This would make the tag-plugin so much more useful to me, as I could use tags mid sentence and not only for blocks.

If you can point me to the file which handles the rendering based on the style-attribute I can give it a shot.

**Comment by LarsGit223** [comment]
Have a look at the file ```helper.php```, look at these functions:
- startList
- addPage
- finishList

**Comment by kruff-a-lon** [comment]
Thanks, it wasn't too hard to change it to something functional (but ugly) that did what I wanted , unfortunately I wanted to use it for the tag-plugin and then it became too complicated for a quick hack (at my skill level). 

I might return to this later, but for now consider this closed (the small changes I made are not worth publishing as they don't make a good list with an arbitrary last separator ('or', 'and', '&', etc)).
