### ISSUE TITLE
Make horizontal list by simplelist flag?

### ISSUE THREAD

**Issue by toby3d** [dokufreaks/plugin-pagelist#111]
I did not find any way to make the list horizontal as a simple set of links. It seems that the flags `list` and `simplelist` are identical.

**Comment by Klap-in** [comment]
`simplelist` shows only a list of pages, without extra columns. `list` shows a list of pages as well, but with extra columns if enabled. `table` is rather similar as `list` but with a table layout.

I should understand Horizontal lists as a couple of links on the same line? That is thus different than `simplelist` which is a 'vertical' list.
I have no plans to implement this, but a pull request is possible.
