### ISSUE TITLE
Request: Option to show tags in columns by topic

### ISSUE THREAD

**Issue by reubenfirmin** [dokufreaks/plugin-pagelist#113]
I use the pagelist plugin in combination with tagfilter to produce a filterable summary view of a subset of pages. Along with each page, I show all of the tags, which give information about the item described by the page.

It works great, but one additional enhancement would be an option that organizes tags into columns by topic. So, if there was a topic "state" and a series of tags like "state:in_progress", "state:broken", "state:backlog" then pagelist would create a column named "state" and show values "in progress", "broken", "backlog" in cells in that that column.

**Comment by Klap-in** [comment]
The pagelist will just list what is offered. If the tagfilter plugin does not provide the tags column, but as alternative columns for each "tag topic"/"tag namespace", the pagelist plugin can show this. In `addPage()` the tagfilter can add for each column the html of the respectively tags.

So this can be implemented the best by the tagfilter plugin.
