### ISSUE TITLE
Can there be a way to use pagination the listings?

### ISSUE THREAD

**Issue by Hitch42** [dokufreaks/plugin-pagelist#117]
When displaying a group of pages, by namespace or tag or such, the table will list every page in that category. In some instances, this can lead to a table several hundred rows long. The ability to use pagination in the results, so that only a certain amount are shown at a time, would be very useful. Maybe it could be displayed as a [DataTable](https://datatables.net/) or be made compatible with the [DataTables](https://www.dokuwiki.org/plugin%3Adatatables) plugin.

**Comment by Klap-in** [comment]
Duplicate of #138
