### ISSUE TITLE
Natural sort order

### ISSUE THREAD

**Issue by WJTrevino** [dokufreaks/plugin-pagelist#122]
Can the option to sort with "natural" ordering be added so titles like 2.10 can be sorted below 2.2? This could be minimally invasive by adding an `nsort` option which would use `strnatcmp` instead of `strcmp`.

```php
$fnc = create_function('$a, $b', 'return strnatcmp(noNS($a["id"]), noNS($b["id"])); ');
```

**Comment by Klap-in** [comment]
Fixed by #153

`sortby=title` will sort by title which uses natural sorting with collator(=with support of sorting in the language of your wiki).
