### ISSUE TITLE
Does not work after Hogfather update

### ISSUE THREAD

**Issue by ingof** [dokufreaks/plugin-pagelist#124]
I updated the dokuwiki to Hogfather on my Synology.
Now the plugin is failing with following error:
`Fatal error: Declaration of syntax_plugin_pagelist::handle($match, $state, $pos, &$handler) must be compatible with dokuwiki\Extension\SyntaxPlugin::handle($match, $state, $pos, Doku_Handler $handler) in /volume1/web/dokuwiki/lib/plugins/pagelist/syntax.php on line 0
`

**Comment by michitux** [comment]
Are you sure you have the current version of this plugin installed? This should be fixed in the current version.

**Comment by Klap-in** [comment]
Fixed by ceb4a8863574e8100dcf8ed4a7bc1306d27b08a2
