### ISSUE TITLE
Marked as not compatible with Hogfather on dokuwiki.org/plugin:pagelist

### ISSUE THREAD

**Issue by erik-alm** [dokufreaks/plugin-pagelist#125]
This plugin is marked as not compatible with Hogfather at the https://www.dokuwiki.org/plugin:pagelist page.

What is the exact problem, and can it be added to this list of issues?

Or is dokuwiki.org not the authoritative page on version compatibility for this plugin? And if so, is there some other place to look instead?

**Comment by Klap-in** [comment]
The wiki page shoe the right status.
The person marking the plugin as not compatible does not add a summary with background, so the reasoning is unknown.

Do you use the plugin, an does it work for you? Did you also test maybe on php8?

**Comment by Klap-in** [comment]
If this plugin was not updated, #124 could be an issue, but today we are quite some years further.. So I assume it is not relevant.

**Comment by erik-alm** [comment]
I'm testing it now in PHP 7.4 but I'm not using it directly, only through third-party plugins (tags? nspages?) that have it as a system requirement, but all those plugins seem to work as they're supposed to.

Could be spam voting... or for that matter an unrelated problem.

**Comment by ParoTheParrot** [comment]
WHO is willing and able to change the status on the official plug-page (https://www.dokuwiki.org/plugin:pagelist) ?
I‘m just before an upüdate and uncertain …

**Comment by Klap-in** [comment]
We did not receive reports of real errors.
So I do not know of issues. I will change the status. Don’t hesitate to come back here if you have questions.

**Comment by erik-alm** [comment]
The plugin is marked as Hogfather-compatible on the plugin page now. I'm closing this case.

Thanks for a great plugin!

/E
