### ISSUE TITLE
Deleted comments are not removed from the list {{threads>*&table}}

### ISSUE THREAD

**Issue by Chris75forumname** [dokufreaks/plugin-pagelist#127]
Hi,
I use `{{threads>*&table}}` on my Start page. Apparently, if comments are deleted on the page of origin, they are not removed from this list on the Start page. Is this a bug or did I just mess too much with the code and screwed it up myself??
Yours, Chris

**Comment by Klap-in** [comment]
This is an issue with the Discussion plugin, therefore this is submitted in the wrong issue tracker. (btw it will be solved by https://github.com/dokufreaks/plugin-discussion/issues/226)
