### ISSUE TITLE
resolve_pageid() is deprecated. ("Igor")

### ISSUE THREAD

**Issue by fiwswe** [dokufreaks/plugin-pagelist#134]
…/data/log/deprecated/*.log entries such as:
`2022-09-06 15:32:38		resolve_pageid() is deprecated. It was called from syntax_plugin_pagelist::handle() in /dokuwiki-test/lib/plugins/pagelist/syntax.php:62 dokuwiki\File\PageResolver should be used instead!`

This is unter DW 2022-07-31 "Igor".

Not sure if the suggested fix would still work in Hogfather? There is no …/inc/File/PageResolver.php in Hogfather. Until all of the relevant plugins and themes are compatible to Igor (and PHP 8) I'm still running some Hogfather Wikis.

fiwswe

**Comment by dregad** [comment]
What about conditional code, checking if DokuWiki version is Igor or later then use PageResolver, and execute the legacy code otherwise ? This way backwards-compatibility can be maintained, until you decide to drop it.

**Comment by Klap-in** [comment]
Pull request is welcome, if so please to this branch #130

**Comment by dregad** [comment]
> Pull request is welcome, if so please to this branch #130

Done => #135
