### ISSUE TITLE
Mask for Tagcloud entries

### ISSUE THREAD

**Issue by senorandy** [dokufreaks/plugin-pagelist#19]
It has already been discussed over on the tag plug-in page that it is not possible to create tags in capital letters.

To get around this would it be possible to configure masks for the tags within the cloud plug-in.

Either in in the admin area or in the cloud string itself:

TAGCLOUD ;one_of_my_tags=One_Of_My_Tags;another_one=Another_One

The reason for asking is that I have some abbreviations which are not easily recognisable and would really benefit from being capitalised..

**Comment by LarsGit223** [comment]
This is outdated and also not related to the pagelist plugin.
