### ISSUE TITLE
Option/flag to show parent namespace path of listed pages

### ISSUE THREAD

**Issue by martinus33** [dokufreaks/plugin-pagelist#26]
When listing pages for example  with the Tag Plugin, it would be great to be able to display X parent levels of pages containing the tag.

Would be useful for example if you tag a page "hotpage", to mean the page is to be kept updated then we could be able to list all of theses with their corresponding namespace path in the [start] page.

What do you think ?

**Comment by Klap-in** [comment]
I will not implement this, as it is probably a to specific use. However, you can implement it probably rather similar as above, but by using `curNS($id)`.
