### ISSUE TITLE
{{searchtag}} Is there a way to hide the category dropdown menu ?

### ISSUE THREAD

**Issue by trebmuh** [dokufreaks/plugin-pagelist#48]
I'm a discovering searchtag and didn't find something in the doc (https://www.dokuwiki.org/plugin:tag#searchtags) to achieve this. I was looking at going from here :
![searchtag](https://cloud.githubusercontent.com/assets/8705846/8891216/ccf3512c-3320-11e5-8e2c-7247b825d66c.png)
to something which could looks like:
![searchtag2](https://cloud.githubusercontent.com/assets/8705846/8891219/db1e33c0-3320-11e5-9e67-8e0de323017a.png)

**Comment by LarsGit223** [comment]
This is a feature request that has to be placed in the tag plugin.

**Comment by trebmuh** [comment]
Sorry for the noise, my mistake.
Done here : https://github.com/dokufreaks/plugin-tag/issues/185
