### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by StefanOfDenmark** [dokufreaks/plugin-pagelist#82]
Having the choice to sort the list by date or page name would make this plugin perfect for me.

**Comment by Klap-in** [comment]
According the manual sorting by page should already exist... see the `rsort` and `sort` options.

**Comment by StefanOfDenmark** [comment]
The `sort` and 'rsort' 
> sorts the pages (reverse) alphabetically by pagename
I'm asking for an option to sort by date (a choice between create date and last modify date would be cool).

Best regards

**Comment by StefanOfDenmark** [comment]
I needed this specifically for the Topic function of the Tag plugin, but it turns out that Tag already supports this via the sortkey setting.

I thought Pagelist was resposible for the sorting. My apologies for mixing up the two plugins.

Best regards
