### ISSUE TITLE
Date column value cannot be covered by other plugin

### ISSUE THREAD

**Issue by qwe852147** [dokufreaks/plugin-pagelist#97]
The  value of date column isn't accept date by other plugin set ex discussion plugin.
I want to show discussion last comment time . 
The plugin also set comment time to date column value but date column value always show the page last modify time not comment time

**Comment by LarsGit223** [comment]
Hi!

I am working on some improvements to the pagelist plugin, see branch ```improvements```. Commit 7edcf936c3dbc54aadc95975bb63675847f606bf should solve your problem. Maybe you like to test with that branch. It is work in progress but it would be nice if others test it to.

If you do not want to display the "normal" date column then you should disable it.

Greetings,
Lars

**Comment by qwe852147** [comment]
Thanks, I'll try it .

**Comment by Klap-in** [comment]
In #153 if the date field is filled, it is not overwritten anymore. Before for some of the `showdate` settings, it was still overwritten.
